### ISSUE TITLE
No documentation for compress or decompress

### ISSUE THREAD

**Issue by sampotter** [navjotk/pyzfp#26]
Seems trivial, but it would be helpful to have some basic documentation for `pyzfp.compress` and `pyzfp.decompress`. From IPython on Jupyter, it should be possible to type e.g. `?pyzfp.compress` and get some basic information about parameters required and how they work. Right now I get:

```
In [3]: ?pyzfp.compress
Docstring: <no docstring>
Type:      builtin_function_or_method

In [4]: ?pyzfp.decompress
Docstring: <no docstring>
Type:      builtin_function_or_method
```

**Comment by navjotk** [comment]
Hi Sam
Thanks for the issue. I agree that it's important to have docstrings. 

I'm sorry, this is a side project stemming from something that was itself a side project so I haven't had much time for this. 

I would welcome a PR adding docstrings, if you have the time to contribute to the project?
