### ISSUE TITLE
Parallel flag is ignored on decompress

### ISSUE THREAD

**Issue by ikriv** [navjotk/pyzfp#27]
pyzfp.pyx, line 225 has setting the parallel flag commented out:

```

   #if(parallel):
   #    zfp_stream_set_execution(stream, zfp_exec_omp)

```
Is it done on purpose? Should we expect bugs with parallel decompress?

**Comment by navjotk** [comment]
ZFP, the underlying compression library, does [not support](https://zfp.readthedocs.io/en/release0.5.5/execution.html#parallel-decompression) parallel decompression.
