### ISSUE TITLE
errors while installing pyzfp

### ISSUE THREAD

**Issue by pythonmobile** [navjotk/pyzfp#28]
Building wheel for pyzfp (setup.py): started
Building wheel for pyzfp (setup.py): finished with status 'error'
ERROR: Command errored out with exit status 1:

x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c /tmp/tmpzna6psc5.cpp -o tmp/tmpzna6psc5.o -fopenmp

error: HTTPSConnectionPool(host='computing.llnl.gov', port=443): Max retries exceeded with url: /system/files/zfp-0.5.5.tar.gz (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

I think https://computing.llnl.gov/system/files/zfp-0.5.5.tar.gz - this file is no longer present and needs to be replaced with the github link for downloading the file in - setup.py?

**Comment by zuspiel** [comment]
Seeing this as well.

**Comment by navjotk** [comment]
Thanks for pointing this out. I have now fixed this.

**Comment by pythonmobile** [comment]
Thanks @navjotk - Is there any hope of updating this repo with the newer versions/master of zfp code that is on github?

**Comment by navjotk** [comment]
This repo is now up to date with the latest zfp.

**Comment by tripti-agarwal** [comment]
I still get the same issue

**Comment by navjotk** [comment]
I can't see how the current code could lead to the exact same error. Can you post the stack trace of your error please?

**Comment by tripti-agarwal** [comment]
tripti@axiom:~$ pip3 install pyzfp
Collecting pyzfp
  Using cached pyzfp-0.5.5.tar.gz (257 kB)
Building wheels for collected packages: pyzfp
  Building wheel for pyzfp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_wb0zr6o/pyzfp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_wb0zr6o/pyzfp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-jz5c6ihh
       cwd: /tmp/pip-install-_wb0zr6o/pyzfp/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_ext
  creating tmp
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c /tmp/tmpqjl7wqoq.cpp -o tmp/tmpqjl7wqoq.o -fopenmp
  Will execute the following command in with subprocess.Popen:
  make OPENMP=1
  b"git clone -b release0.5.5 https://github.com/LLNL/zfp.git zfp-0.5.5\nCloning into 'zfp-0.5.5'...\ncd zfp-0.5.5 && make\nmake[1]: Entering directory '/tmp/pip-install-_wb0zr6o/pyzfp/zfp-0.5.5'\nstatic\nrm -f ../lib/libzfp.a ../lib/libzfp.so bitstream.o decode1i.o decode1l.o decode1f.o decode1d.o encode1i.o encode1l.o encode1f.o encode1d.o decode2i.o decode2l.o decode2f.o decode2d.o encode2i.o encode2l.o encode2f.o encode2d.o decode3i.o decode3l.o decode3f.o decode3d.o encode3i.o encode3l.o encode3f.o encode3d.o decode4i.o decode4l.o decode4f.o decode4d.o encode4i.o encode4l.o encode4f.o encode4d.o zfp.o\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c bitstream.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode1i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode1l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode1f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode1d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode1i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode1l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode1f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode1d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode2i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode2l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode2f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode2d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode2i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode2l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode2f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode2d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode3i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode3l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode3f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode3d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode3i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode3l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode3f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode3d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode4i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode4l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode4f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode4d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode4i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode4l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode4f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode4d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c zfp.c\nmkdir -p ../lib\nrm -f ../lib/libzfp.a\nar rc ../lib/libzfp.a bitstream.o decode1i.o decode1l.o decode1f.o decode1d.o encode1i.o encode1l.o encode1f.o encode1d.o decode2i.o decode2l.o decode2f.o decode2d.o encode2i.o encode2l.o encode2f.o encode2d.o decode3i.o decode3l.o decode3f.o decode3d.o encode3i.o encode3l.o encode3f.o encode3d.o decode4i.o decode4l.o decode4f.o decode4d.o encode4i.o encode4l.o encode4f.o encode4d.o zfp.o\nrm -f ../bin/zfp fields.o\nmkdir -p ../bin\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  zfp.c -L../lib -lzfp -lm -o ../bin/zfp\nrm -f ../bin/testzfp ../bin/testviews\ng++ -std=c++98 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -I../array testzfp.cpp -L../lib -lzfp -o ../bin/testzfp\ng++ -std=c++98 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -I../array testviews.cpp -L../lib -lzfp -o ../bin/testviews\nmake[1]: Leaving directory '/tmp/pip-install-_wb0zr6o/pyzfp/zfp-0.5.5'\n"
  building 'pyzfp' extension
  creating build
  creating build/temp.linux-x86_64-3.9
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Izfp-0.5.5/include -I/home/tripti/.local/lib/python3.9/site-packages/numpy/core/include -I/usr/include/python3.9 -c pyzfp.c -o build/temp.linux-x86_64-3.9/pyzfp.o -fopenmp
  pyzfp.c:35:10: fatal error: Python.h: No such file or directory
     35 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pyzfp
  Running setup.py clean for pyzfp
Failed to build pyzfp
Installing collected packages: pyzfp
    Running setup.py install for pyzfp ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_wb0zr6o/pyzfp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_wb0zr6o/pyzfp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a8vb7gc4/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/tripti/.local/include/python3.9/pyzfp
         cwd: /tmp/pip-install-_wb0zr6o/pyzfp/
    Complete output (16 lines):
    running install
    running build
    running build_ext
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c /tmp/tmplaoq6wcr.cpp -o tmp/tmplaoq6wcr.o -fopenmp
    Will execute the following command in with subprocess.Popen:
    make OPENMP=1
    b"cd zfp-0.5.5 && make\nmake[1]: Entering directory '/tmp/pip-install-_wb0zr6o/pyzfp/zfp-0.5.5'\nstatic\nrm -f ../lib/libzfp.a ../lib/libzfp.so bitstream.o decode1i.o decode1l.o decode1f.o decode1d.o encode1i.o encode1l.o encode1f.o encode1d.o decode2i.o decode2l.o decode2f.o decode2d.o encode2i.o encode2l.o encode2f.o encode2d.o decode3i.o decode3l.o decode3f.o decode3d.o encode3i.o encode3l.o encode3f.o encode3d.o decode4i.o decode4l.o decode4f.o decode4d.o encode4i.o encode4l.o encode4f.o encode4d.o zfp.o\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c bitstream.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode1i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode1l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode1f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode1d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode1i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode1l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode1f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode1d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode2i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode2l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode2f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode2d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode2i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode2l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode2f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode2d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode3i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode3l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode3f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode3d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode3i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode3l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode3f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode3d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode4i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode4l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode4f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c decode4d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode4i.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode4l.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode4f.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c encode4d.c\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -c zfp.c\nmkdir -p ../lib\nrm -f ../lib/libzfp.a\nar rc ../lib/libzfp.a bitstream.o decode1i.o decode1l.o decode1f.o decode1d.o encode1i.o encode1l.o encode1f.o encode1d.o decode2i.o decode2l.o decode2f.o decode2d.o encode2i.o encode2l.o encode2f.o encode2d.o decode3i.o decode3l.o decode3f.o decode3d.o encode3i.o encode3l.o encode3f.o encode3d.o decode4i.o decode4l.o decode4f.o decode4d.o encode4i.o encode4l.o encode4f.o encode4d.o zfp.o\nrm -f ../bin/zfp fields.o\nmkdir -p ../bin\ngcc -std=c99 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  zfp.c -L../lib -lzfp -lm -o ../bin/zfp\nrm -f ../bin/testzfp ../bin/testviews\ng++ -std=c++98 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -I../array testzfp.cpp -L../lib -lzfp -o ../bin/testzfp\ng++ -std=c++98 -O3 -fPIC -Wall -Wextra -pedantic -I../include -fopenmp  -I../array testviews.cpp -L../lib -lzfp -o ../bin/testviews\nmake[1]: Leaving directory '/tmp/pip-install-_wb0zr6o/pyzfp/zfp-0.5.5'\n"
    building 'pyzfp' extension
    creating build
    creating build/temp.linux-x86_64-3.9
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Izfp-0.5.5/include -I/home/tripti/.local/lib/python3.9/site-packages/numpy/core/include -I/usr/include/python3.9 -c pyzfp.c -o build/temp.linux-x86_64-3.9/pyzfp.o -fopenmp
    pyzfp.c:35:10: fatal error: Python.h: No such file or directory
       35 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_wb0zr6o/pyzfp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_wb0zr6o/pyzfp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a8vb7gc4/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/tripti/.local/include/python3.9/pyzfp Check the logs for full command output.

**Comment by tripti-agarwal** [comment]
Well, I should not a written a vague comment. 
When I try to install pyzfp, the wheel is unable to build.

This is was the error is:

 pyzfp.c:35:10: fatal error: Python.h: No such file or directory
     35 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pyzfp

**Comment by navjotk** [comment]
I think this is a very different issue. Looks like you might need the python development libraries. Have you looked at [this](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory)?

I will close this issue now but please feel free to open a new issue if you continue to face problems.
