### ISSUE TITLE
Binary Distributions

### ISSUE THREAD

**Issue by william-silversmith** [navjotk/pyzfp#31]
Hi! 

I'm looking into using pyzfp for https://github.com/seung-lab/cloud-volume. Would it be possible to provide binaries of the library on pypi? It's not hard to set it up. Check out this Github Actions file: 

https://github.com/seung-lab/fastremap/blob/master/.github/workflows/build_wheel.yml

This will create binaries for the most common cPython platforms. The aarch64 (ARM64) builds are virtualized (I believe) and take longer than the others, but could be omitted if it's excessive.

Thanks so much for this wonderful package!

**Comment by navjotk** [comment]
Thanks for the suggestion. I'll look into this.

**Comment by navjotk** [comment]
@william-silversmith Created a PR to do this. Do you mind helping review?
